<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="bibliotheque">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="livre" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="titre" type="xs:string"/>
              <xs:element name="auteur" type="xs:string"/>
              <xs:element name="annee" type="xs:gYear"/>
              <xs:element name="genre" type="xs:string"/>
              <xs:element name="disponible" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:integer" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>
